### PR TITLE
Add sigfig to scores so that we can continue chasing perfection

### PR DESCRIPTION
**Pull request by jacknoble**
Ont wins round one.

### CODE REVIEW

**Comment by Supernats** [comment]
[Obligatory](http://www.youtube.com/watch?v=OHbtcvk_KBs)

**Comment by Supernats** [comment]
:+1:

**Comment by Supernats** [comment]
This is cool for now, but in the future I think we should actually drop the sigfig level and have it auto reset everyone on some regular schedule or after x dubs achieve nirvana.

**Comment by jacknoble** [comment]
Ont has 0.5 meta bum bums???

**Comment by gotno** [comment]
:+1:

**Comment by gotno** [comment]
wait why is rounding down if i'm at 0.5?

**Comment by gotno** [comment]
JAVASCRIPT...

**Pull request merged**
